spring:
  shardingsphere:
    datasource:
      names: db
      db:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://172.18.29.211:5432/postgres
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        # 初始连接数
        initial-size: 5
        # 最小连接数
        min-idle: 5
        # 最大连接数
        max-active: 20
        # 获取连接最大等待时间
        max-wait: 800
        # 连接池空闲连接的有效时间   5分钟
        min-evictable-idle-time-millis: 300000

        keep-alive: true

        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        filters: stat,wall

        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 1000

        web-stat-filter:
          enabled: true
        # loaclhost:端口/druid/login.html
#        stat-view-servlet:
#          enabled: true
#          login-username: admin
#          login-password: admin
    rules:
      sharding:
        tables:
          building_entity:
            actual-data-nodes: db.building_entity_$->{0..1}
            table-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: building_entity-inline
        sharding-algorithms:
          building_entity-inline:
            type: INLINE
            props:
              algorithm-expression: building_entity_$->{id % 2}
              allow-range-query-with-inline-sharding: true
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
