version: "3"
services:
  zookeeper:
    container_name: my_zookeeper
    image: zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    container_name: my_kafka
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: 172.18.27.213
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.18.27.213:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
