version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [ nosniff ]
    Access-Control-Allow-Origin: [ '*' ]
    Access-Control-Allow-Methods: [ 'HEAD', 'GET', 'OPTIONS', 'DELETE' ]
    Access-Control-Allow-Headers: [ 'Authorization', 'Accept' ]
    Access-Control-Max-Age: [ 1728000 ]
    Access-Control-Allow-Credentials: [ true ]
    Access-Control-Expose-Headers: [ 'Docker-Content-Digest' ]
  http2:
    disabled: false
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
